=== TRaSH-Guides/Guides/schemas/guide-only-cf.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "trash_id": {
      "$ref": "base-cf.schema.json#/defs/trash_id"
    },
    "trash_scores": {
      "$ref": "base-cf.schema.json#/defs/trash_scores"
    },
    "trash_regex": {
      "$ref": "base-cf.schema.json#/defs/trash_regex"
    },
    "trash_description": {
      "$ref": "base-cf.schema.json#/defs/trash_description"
    },
    "name": {
      "$ref": "base-cf.schema.json#/defs/name"
    },
    "includeCustomFormatWhenRenaming": {
      "type": "boolean"
    },
    "specifications": {
      "type": "array",
      "items": {
        "anyOf": [
          { "$ref": "specs/release-title-spec.json" },
          { "$ref": "specs/edition-spec.json" },
          { "$ref": "specs/language-spec.json" },
          { "$ref": "specs/indexer-flag-spec.json" },
          { "$ref": "specs/source-spec.json" },
          { "$ref": "specs/resolution-spec.json" },
          { "$ref": "specs/quality-modifier-spec.json" },
          { "$ref": "specs/size-spec.json" },
          { "$ref": "specs/release-group-spec.json" },
          { "$ref": "specs/release-type-spec.json" },
          { "$ref": "specs/year-spec.json" }
        ]
      },
      "minItems": 1
    }
  },
  "required": [
    "trash_id",
    "name",
    "includeCustomFormatWhenRenaming",
    "specifications"
  ],
  "additionalProperties": false
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf/lq.json
{
  "trash_id": "9c11cd3f07101cdba90a2d81cf0e56b4",
  "trash_scores": {
    "default": -10000,
    "german": -35000,
    "german-anime": -35000
  },
  "name": "LQ",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "126811",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(126811)$"
      }
    },
    {
      "name": "BRiNK",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(BRiNK)$"
      }
    },
    {
      "name": "BTM",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(BTM)$"
      }
    },
    {
      "name": "CHX",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(CHX)$"
      }
    },
    {
      "name": "CTFOH",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(CTFOH)$"
      }
    },
    {
      "name": "d3g",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(d3g)$"
      }
    },
    {
      "name": "DepraveD",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(DepraveD)$"
      }
    },
    {
      "name": "EVO",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(EVO)$"
      }
    },
    {
      "name": "Feranki1980",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(Feranki1980)$"
      }
    },
    {
      "name": "FGT",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(FGT)$"
      }
    },
    {
      "name": "FMD",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(FMD)$"
      }
    },
    {
      "name": "GHOSTS",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(GHOSTS)$"
      }
    },
    {
      "name": "HiQVE",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(HiQVE)$"
      }
    },
    {
      "name": "iNTENSO",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(iNTENSO)$"
      }
    },
    {
      "name": "iVy",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(iVy)$"
      }
    },
    {
      "name": "JFF",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(JFF)$"
      }
    },
    {
      "name": "KC",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(KC)$"
      }
    },
    {
      "name": "MeGusta",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(MeGusta)$"
      }
    },
    {
      "name": "nhanc3",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(nhanc3)$"
      }
    },
    {
      "name": "OFT",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(OFT)$"
      }
    },
    {
      "name": "Pahe",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "Pahe(\\.(ph|in))?\\b"
      }
    },
    {
      "name": "PSA",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(PSA)$"
      }
    },
    {
      "name": "SasukeducK",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(SasukeducK)$"
      }
    },
    {
      "name": "SHD",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(SHD)$"
      }
    },
    {
      "name": "ShieldBearer",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(ShieldBearer)$"
      }
    },
    {
      "name": "TBS",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(TBS)$"
      }
    },
    {
      "name": "TG",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(TG)$"
      }
    },
    {
      "name": "VIDEOHOLE",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(VIDEOHOLE)$"
      }
    },
    {
      "name": "worldmkv",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(worldmkv)$"
      }
    },
    {
      "name": "XLF",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(XLF)$"
      }
    },
    {
      "name": "Zero00",
      "implementation": "ReleaseGroupSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": "^(Zero00)$"
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf/language-not-german-english.json
{
  "trash_id": "133589380b89f8f8394320901529bac1",
  "trash_scores": {
      "default": -20000
  },
  "name": "Not German or English",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Not English Language",
      "implementation": "LanguageSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": 1
      }
    },
    {
      "name": "Not German Language",
      "implementation": "LanguageSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": 4
      }
    },
    {
      "name": "Not German in Title",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "(?i)\\bgerman\\b"
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf/wetv.json
{
  "trash_id": "e0ae51a2508ab62ffb1af027f3717486",
  "trash_scores": {
    "default": 30
  },
  "name": "WETV",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "WETV",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\b(WETV)\\b"
      }
    },
    {
      "name": "WEBDL",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 3
      }
    },
    {
      "name": "WEBRIP",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 4
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf/atmos-undefined.json
{
  "trash_id": "417804f7f2c4308c1f4c5d380d4c4475",
  "trash_scores": {
    "default": 3000,
    "sqp-1-1080p": 0,
    "sqp-1-web-1080p": 0,
    "sqp-1-2160p": 0,
    "sqp-1-web-2160p": 0,
    "sqp-4-ma-hybrid": 480
  },
  "name": "ATMOS (undefined)",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "ATMOS",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\bATMOS(\\b|\\d)"
      }
    },
    {
      "name": "Not AAC",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bAAC(\\b|\\d)"
      }
    },
    {
      "name": "Not Basic Dolby Digital ",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bDD[^a-z+]|(?<!e-)\\b(ac-?3)\\b"
      }
    },
    {
      "name": "Not Dolby Digital Plus",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bDD[P+]|\\b(e[-_. ]?ac-?3)\\b"
      }
    },
    {
      "name": "Not DTS",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bDTS(\\b|\\d)"
      }
    },
    {
      "name": "Not FLAC",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\bFLAC(\\b|\\d)"
      }
    },
    {
      "name": "Not PCM",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\b(l?)PCM(\\b|\\d)"
      }
    },
    {
      "name": "Not RlsGrp (Atmos Only)",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "\\b(W4NK3R|HQMUX)\\b"
      }
    },
    {
      "name": "Not TrueHD",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": true,
      "fields": {
        "value": "True[ .-]?HD"
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf/with-basl.json
{
  "trash_id": "41e4baea7b10ddefc6609d52f742dacd",
  "trash_regex": "https://regex101.com/r/iCyLwn/1",
  "name": "WiTH BASL",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "Black American Sign Language",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\b(BASL)\\b"
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/sonarr/cf/hulu.json
{
  "trash_id": "f6cce30f1733d5c8194222a7507909bb",
  "trash_scores": {
    "default": 50
  },
  "name": "HULU",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "Hulu",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\b(hulu)\\b"
      }
    },
    {
      "name": "WEBDL",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 3
      }
    },
    {
      "name": "WEBRIP",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 4
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/radarr/cf/language-prefer-spanish.json
{
  "trash_id": "language-prefer-spanish",
  "trash_scores": {
    "default": 10
  },
  "trash_description": "Prefer Language X",
  "name": "Spanish",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "Spanish Language",
      "implementation": "LanguageSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 3
      }
    }
  ]
}

=== TRaSH-Guides/Guides/docs/json/radarr/hmax.json
{
  "trash_id": "5763d1b0ce84aff3b21038eea8e9b8ad",
  "name": "HMAX",
  "includeCustomFormatWhenRenaming": true,
  "specifications": [
    {
      "name": "HBO Max",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": "\\b(hmax|hbom|HBO Max)\\b"
      }
    },
    {
      "name": "WEBDL",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 7
      }
    },
    {
      "name": "WEBRIP",
      "implementation": "SourceSpecification",
      "negate": false,
      "required": false,
      "fields": {
        "value": 8
      }
    }
  ]
}
